### ISSUE TITLE
Simple Way to override the cache

### ISSUE THREAD

**Issue by nharrisanalyst** [americanexpress/iguazu-graphql#11]
💡 

In my application the user has a drop down menu that returns data for different customers. 
If the data is returned with an error and the user switches to another customer and than back to the customer that had previously returned an error instead of making the call again iguazu-graphql hits the cache returning the same error.

Having a way to check to override the cache would be great.
Even having a section in the docs explaining the cache would be great.

**Comment by msanfilippof** [comment]
> Having a way to check to override the cache would be great.
@nharrisanalyst I think there's already a `forceFetch` for this, right?

**Comment by 10xLaCroixDrinker** [comment]
Closing as this library is no longer maintained
