### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nharrisanalyst** [americanexpress/iguazu-graphql#3]
I have followed along exactly with the examples but I keep getting this error 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/16217396/72746479-0b91db80-3b67-11ea-8041-500b40b1916c.png">

It is also odd because on Chrome with the same app I get this error 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/16217396/72746552-3f6d0100-3b67-11ea-9de9-16cf304f100a.png">

**Comment by nharrisanalyst** [comment]
I have tried googling but have hit a brick wall maybe you could give me some direction on what this means?

**Comment by nharrisanalyst** [comment]
I just figured it out from the code the graphQL reducer has to be named "iguazuGraphQL"

**Comment by anescobar1991** [comment]
@nharrisanalyst do you want to open a pull request to augment the docs so that others don't face this same issue again?
