### ISSUE TITLE
Stack blows when setting forceFetch to true

### ISSUE THREAD

**Issue by nharrisanalyst** [americanexpress/iguazu-graphql#8]
## Describe the bug
Stack blows when setting for fetch to true

## To Reproduce
set forceFetch to true

## Expected behavior

Call is only made one time 

<img width="939" alt="image" src="https://user-images.githubusercontent.com/16217396/75499786-ecfddc00-597f-11ea-913e-dc655a90346e.png">

I am trying to control the cache I thought setting force fetch to true that that would make a new query and bi pass the cahce but it seems to just blow the stack through making countless queries.

**Comment by msanfilippof** [comment]
@nharrisanalyst is still still an open issue? I had something similar in the past but if you can share a larger code snippet I may give some suggestions.

**Comment by 10xLaCroixDrinker** [comment]
Closing as this library is no longer maintained
